apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
spec:
  capacity:
    storage: 5Gi  # You can adjust the size depending on your needs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: shared-storage  # Reference the StorageClass
  hostPath:
    path: /data/shared  # Path on the host machine
    type: DirectoryOrCreate
